# Generated by Django 6.0.2 on 2026-02-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_molecule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='molecule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='molecule',
            name='is_show',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='molecule',
            name='formula',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='molecule',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='molecule',
            name='smiles',
            field=models.TextField(),
        ),
    ]
