# Generated by Django 6.0.2 on 2026-06-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_molecule', '0002_molecule_created_at_molecule_is_show_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='molecule',
            old_name='smiles',
            new_name='coordinates',
        ),
        migrations.RemoveField(
            model_name='molecule',
            name='formula',
        ),
        migrations.AddField(
            model_name='molecule',
            name='format',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='molecule',
            name='type',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
