# Generated by Django 6.0.2 on 2026-06-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_molecule', '0003_rename_smiles_molecule_coordinates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='molecule',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
